# Generated by Django 4.2.5 on 2023-10-06 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='port_name',
            new_name='portfolio_name',
        ),
    ]
